//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employees()
        {
            this.interventions = new HashSet<interventions>();
            this.localizations = new HashSet<localizations>();
        }
    
        public int id { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string social_security_number { get; set; }
        public string email { get; set; }
        public int role_id { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string marital_status { get; set; }
        public System.DateTime birthdate { get; set; }
        public System.DateTime arrival_date { get; set; }
        public string bank_account { get; set; }
        public string street_number { get; set; }
        public string street_name { get; set; }
        public string zip_code { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public byte[] picture { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual roles roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<interventions> interventions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<localizations> localizations { get; set; }
    }
}
